### PR TITLE
Json builder preview mvp

### PR DESCRIPTION
**Pull request by RomanMunar**

### CODE REVIEW

**Comment by RomanMunar** [comment]
@crtved  Still an early version of the concept. Usable for common scenarios. We'll include a link in the home page or '/' route once we've ironed edge cases.

**Comment by RomanMunar** [comment]
link: `https://chklst-8h43akwx4-crtved.vercel.app/json-builder`

**Review by artsandiego — COMMENTED** [review]
Galing! Thank you @RomanMunar.
Pa pull ng new update, there are some changes sa handling ng data, I'll push tonight para you can have the latest version including the dynamic json file reader.

below are the items we probably need to address.

- [ ] Generated json data cannot be parsed because of non-quoted object key
- [ ] Ability to remove tags

**Comment by RomanMunar** [comment]
- [ ] Generated json data cannot be parsed because of non-quoted object key
    - oops, I explicitly removed them, I'll add them back.
- [ ] Ability to remove tags
    - Should be easy, I just don't know to display them, I'll try to implement this tomorrow na.
- [ ] Refactor to multiple files
- [ ] Mobile display
- [ ] Link to home page

**Pull request merged**
